# pylint: disable=too-many-lines
"""
IQ Option Asset Constants
Date: 2026-04-17 14:03:22
"""

ACTIVES = {
    "EURUSD": 1,                             # forex
    "EURGBP": 2,                             # forex
    "GBPJPY": 3,                             # forex
    "EURJPY": 4,                             # forex
    "GBPUSD": 5,                             # forex
    "USDJPY": 6,                             # forex
    "AUDCAD": 7,                             # forex
    "NZDUSD": 8,                             # forex
    "USDRUB": 10,                            # opcode
    "AMAZON": 31,                            # stock
    "APPLE": 32,                             # stock
    "BAIDU": 33,                             # stock
    "CISCO": 34,                             # stock
    "FACEBOOK": 35,                          # stock
    "GOOGLE": 36,                            # stock
    "INTEL": 37,                             # stock
    "MSFT": 38,                              # stock
    "AIG": 41,                               # stock
    "CITI": 45,                              # stock
    "COKE": 46,                              # stock
    "GE": 48,                                # stock
    "GM": 49,                                # stock
    "GS": 50,                                # stock
    "JPM": 51,                               # stock
    "MCDON": 52,                             # stock
    "MORSTAN": 53,                           # stock
    "NIKE": 54,                              # stock
    "SONYNK": 60,                            # stock
    "USDCHF": 72,                            # forex
    "XAUUSD": 74,                            # commodity
    "XAGUSD": 75,                            # opcode
    "EURUSD-OTC": 76,                        # forex
    "EURGBP-OTC": 77,                        # forex
    "USDCHF-OTC": 78,                        # forex
    "EURJPY-OTC": 79,                        # forex
    "NZDUSD-OTC": 80,                        # forex
    "GBPUSD-OTC": 81,                        # forex
    "GBPJPY-OTC": 84,                        # forex
    "USDJPY-OTC": 85,                        # forex
    "AUDCAD-OTC": 86,                        # forex
    "ALIBABA": 87,                           # stock
    "ITAUBANCO": 89,                         # stock
    "AUDUSD": 99,                            # forex
    "USDCAD": 100,                           # forex
    "AUDJPY": 101,                           # forex
    "GBPCAD": 102,                           # forex
    "GBPCHF": 103,                           # forex
    "GBPAUD": 104,                           # forex
    "EURCAD": 105,                           # forex
    "CHFJPY": 106,                           # forex
    "CADCHF": 107,                           # forex
    "EURAUD": 108,                           # forex
    "FERRARI": 133,                          # stock
    "TESLA": 167,                            # stock
    "USDNOK": 168,                           # forex
    "EURNZD": 212,                           # forex
    "USDSEK": 219,                           # forex
    "USDTRY": 220,                           # forex
    "MMM:US": 252,                           # stock
    "ABT:US": 253,                           # stock
    "ABBV:US": 254,                          # stock
    "ACN:US": 255,                           # stock
    "ADBE:US": 258,                          # stock
    "AAP:US": 259,                           # opcode
    "AMG:US": 262,                           # stock
    "AA:US": 269,                            # stock
    "MO:US": 278,                            # stock
    "AAL:US": 281,                           # stock
    "AXP:US": 283,                           # stock
    "AMGN:US": 290,                          # stock
    "AMAT:US": 299,                          # stock
    "T:US": 303,                             # stock
    "ADSK:US": 304,                          # stock
    "AVGO:US": 308,                          # stock
    "BAC:US": 313,                           # stock
    "BRK-B:US": 319,                         # stock
    "BBY:US": 320,                           # stock
    "BLK:US": 322,                           # stock
    "BA:US": 324,                            # stock
    "BMY:US": 328,                           # stock
    "CCL:US": 337,                           # stock
    "CAT:US": 338,                           # stock
    "SCHW:US": 347,                          # stock
    "CVX:US": 349,                           # stock
    "CTAS:US": 356,                          # stock
    "CL:US": 365,                            # stock
    "CMCSA:US": 366,                         # stock
    "COP:US": 370,                           # stock
    "ED:US": 371,                            # stock
    "COST:US": 374,                          # stock
    "CVS:US": 379,                           # stock
    "DHI:US": 380,                           # stock
    "DHR:US": 381,                           # stock
    "DRI:US": 382,                           # stock
    "DVA:US": 383,                           # stock
    "DE:US": 384,                            # stock
    "DAL:US": 386,                           # stock
    "DVN:US": 388,                           # stock
    "DLR:US": 390,                           # stock
    "DFS:US": 391,                           # opcode
    "DTE:US": 400,                           # stock
    "EMN:US": 405,                           # stock
    "EBAY:US": 407,                          # stock
    "ECL:US": 408,                           # stock
    "EIX:US": 409,                           # stock
    "EMR:US": 413,                           # stock
    "ETR:US": 415,                           # stock
    "EQT:US": 417,                           # stock
    "EFX:US": 418,                           # stock
    "EQR:US": 420,                           # stock
    "ESS:US": 421,                           # stock
    "EXPD:US": 426,                          # stock
    "EXR:US": 428,                           # stock
    "XOM:US": 429,                           # stock
    "FFIV:US": 430,                          # stock
    "FRT:US": 433,                           # stock
    "FIS:US": 435,                           # stock
    "FITB:US": 436,                          # stock
    "FSLR:US": 437,                          # stock
    "FE:US": 438,                            # stock
    "FISV:US": 439,                          # opcode
    "FLS:US": 441,                           # stock
    "FMC:US": 443,                           # stock
    "F:US": 446,                             # stock
    "FBHS:US": 448,                          # stock
    "FCX:US": 450,                           # stock
    "GPS:US": 452,                           # stock
    "GILD:US": 460,                          # stock
    "HAS:US": 471,                           # stock
    "HD:US": 479,                            # stock
    "HON:US": 480,                           # stock
    "IBM:US": 491,                           # stock
    "INTU:US": 495,                          # stock
    "JNJ:US": 501,                           # stock
    "KHC:US": 513,                           # stock
    "LLY:US": 524,                           # stock
    "LMT:US": 528,                           # stock
    "LOW:US": 530,                           # stock
    "MA:US": 542,                            # stock
    "MDT:US": 548,                           # stock
    "MU:US": 553,                            # stock
    "MDLZ:US": 557,                          # stock
    "NFLX:US": 569,                          # stock
    "NEE:US": 575,                           # stock
    "NVDA:US": 586,                          # stock
    "ORCL:US": 591,                          # stock
    "PYPL:US": 597,                          # stock
    "PEP:US": 600,                           # stock
    "PFE:US": 603,                           # stock
    "PM:US": 605,                            # stock
    "PG:US": 617,                            # stock
    "PLD:US": 619,                           # stock
    "QCOM:US": 626,                          # stock
    "DGX:US": 628,                           # stock
    "RTN:US": 630,                           # stock
    "RCL:US": 642,                           # stock
    "SPGI:US": 644,                          # stock
    "CRM:US": 645,                           # stock
    "SLB:US": 647,                           # stock
    "LUV:US": 660,                           # stock
    "SBUX:US": 666,                          # stock
    "SYK:US": 670,                           # stock
    "TXN:US": 681,                           # stock
    "DIS:US": 689,                           # stock
    "TJX:US": 693,                           # stock
    "UNP:US": 708,                           # stock
    "UAL:US": 709,                           # stock
    "UPS:US": 711,                           # stock
    "VZ:US": 723,                            # stock
    "V:US": 726,                             # stock
    "WMT:US": 729,                           # stock
    "WBA:US": 730,                           # opcode
    "WFC:US": 733,                           # stock
    "SNAP": 756,                             # stock
    "AMD": 760,                              # stock
    "ALGN": 761,                             # stock
    "ANSS": 762,                             # opcode
    "IDXX": 775,                             # stock
    "NVS": 780,                              # stock
    "RMD": 781,                              # stock
    "SU": 783,                               # stock
    "TFX": 784,                              # stock
    "TMUS": 785,                             # stock
    "TM": 786,                               # stock
    "QQQ": 796,                              # etf
    "SPY": 808,                              # etf
    "BTCUSD": 816,                           # crypto
    "XRPUSD": 817,                           # crypto
    "ETHUSD": 818,                           # crypto
    "LTCUSD": 819,                           # crypto
    "DSHUSD": 821,                           # crypto
    "BCHUSD": 824,                           # crypto
    "ZECUSD": 826,                           # crypto
    "ETCUSD": 829,                           # crypto
    "BTCUSD-L": 830,                         # opcode
    "ETHUSD-L": 831,                         # crypto
    "LTCUSD-L": 834,                         # crypto
    "DSHUSD-L": 835,                         # crypto
    "BCHUSD-L": 836,                         # crypto
    "ADAUSD": 844,                           # crypto
    "QTMUSD": 845,                           # crypto
    "TRXUSD": 858,                           # crypto
    "EOSUSD": 864,                           # crypto
    "USDINR": 865,                           # forex
    "USDPLN": 866,                           # forex
    "USDBRL": 867,                           # forex
    "USDZAR": 868,                           # forex
    "XRPUSD-bitfinex": 881,                  # crypto
    "XRPBTC-bitfinex": 882,                  # crypto
    "LTCUSD-bitfinex": 883,                  # crypto
    "ETHUSD-bitfinex": 885,                  # crypto
    "ETH/BTC": 886,                          # crypto
    "DBX": 889,                              # stock
    "SPOT": 891,                             # stock
    "USDSGD": 892,                           # forex
    "USDHKD": 893,                           # forex
    "LLOYL-CHIX": 894,                       # stock
    "VODL-CHIX": 895,                        # stock
    "BARCL-CHIX": 896,                       # stock
    "TSCOL-CHIX": 897,                       # stock
    "BPL-CHIX": 898,                         # stock
    "HSBAL-CHIX": 899,                       # stock
    "RBSL-CHIX": 900,                        # stock
    "STANL-CHIX": 903,                       # stock
    "RRL-CHIX": 904,                         # stock
    "MKSL-CHIX": 905,                        # stock
    "BATSL-CHIX": 906,                       # stock
    "ULVRL-CHIX": 908,                       # opcode
    "EZJL-CHIX": 909,                        # stock
    "ADSD-CHIX": 910,                        # stock
    "ALVD-CHIX": 911,                        # stock
    "BAYND-CHIX": 912,                       # stock
    "BMWD-CHIX": 913,                        # stock
    "CBKD-CHIX": 914,                        # stock
    "COND-CHIX": 915,                        # stock
    "DBKD-CHIX": 917,                        # stock
    "LHAD-CHIX": 918,                        # stock
    "DPWD-CHIX": 919,                        # stock
    "DTED-CHIX": 920,                        # stock
    "EOAND-CHIX": 921,                       # stock
    "MRKD-CHIX": 922,                        # stock
    "SIED-CHIX": 923,                        # stock
    "TKAD-CHIX": 924,                        # stock
    "VOW3D-CHIX": 925,                       # stock
    "ENELM-CHIX": 926,                       # stock
    "ENIM-CHIX": 927,                        # stock
    "PIRCM-CHIX": 929,                       # stock
    "PSTM-CHIX": 930,                        # stock
    "TITM-CHIX": 931,                        # stock
    "UCGM-CHIX": 932,                        # stock
    "SANE-CHIX": 937,                        # stock
    "BBVAE-CHIX": 938,                       # stock
    "TEFE-CHIX": 939,                        # stock
    "AIRP-CHIX": 940,                        # stock
    "HEIOA-CHIX": 941,                       # stock
    "ORP-CHIX": 942,                         # stock
    "AUDCHF": 943,                           # forex
    "AUDNZD": 944,                           # forex
    "CADJPY": 945,                           # forex
    "EURCHF": 946,                           # forex
    "GBPNZD": 947,                           # forex
    "NZDCAD": 948,                           # forex
    "NZDJPY": 949,                           # forex
    "EURSEK": 950,                           # forex
    "EURNOK": 951,                           # forex
    "CHFSGD": 952,                           # forex
    "EURCNH": 953,                           # forex
    "EURHKD": 954,                           # forex
    "EURSGD": 955,                           # forex
    "USDCNH": 956,                           # forex
    "USDMXN": 957,                           # forex
    "UKOUSD": 969,                           # commodity
    "XPTUSD": 970,                           # commodity
    "USOUSD": 971,                           # commodity
    "AUDDKK": 983,                           # forex
    "AUDNOK": 986,                           # forex
    "AUDSGD": 989,                           # forex
    "CHFNOK": 998,                           # forex
    "CHFSEK": 1000,                          # forex
    "EURDKK": 1007,                          # forex
    "EURPLN": 1009,                          # forex
    "EURZAR": 1011,                          # forex
    "GBPSGD": 1018,                          # forex
    "GBPZAR": 1020,                          # forex
    "NOKJPY": 1024,                          # forex
    "NZDMXN": 1027,                          # forex
    "NZDSGD": 1031,                          # forex
    "PLNJPY": 1035,                          # forex
    "SGDJPY": 1041,                          # forex
    "USDDKK": 1045,                          # forex
    "NZDCHF": 1048,                          # forex
    "EURCZK": 1056,                          # forex
    "USDTHB": 1062,                          # forex
    "CHFHUF": 1065,                          # forex
    "IOTUSD-L": 1116,                        # crypto
    "XLMUSD-L": 1117,                        # crypto
    "NEOUSD-L": 1118,                        # opcode
    "ADAUSD-L": 1119,                        # crypto
    "XRPUSD-L": 1122,                        # crypto
    "EEM": 1203,                             # etf
    "FXI": 1204,                             # etf
    "IWM": 1205,                             # etf
    "GDX": 1206,                             # etf
    "XOP": 1209,                             # etf
    "XLK": 1210,                             # etf
    "XLE": 1211,                             # etf
    "XLU": 1212,                             # etf
    "IEMG": 1213,                            # etf
    "XLY": 1214,                             # etf
    "IYR": 1215,                             # etf
    "SQQQ": 1216,                            # etf
    "EWJ": 1219,                             # etf
    "XLB": 1221,                             # etf
    "DIA": 1222,                             # etf
    "TLT": 1223,                             # etf
    "SDS": 1224,                             # opcode
    "EWW": 1225,                             # etf
    "XME": 1227,                             # etf
    "JNUG": 1228,                            # etf
    "TRXUSD-L": 1242,                        # crypto
    "EOSUSD-L": 1244,                        # opcode
    "BNBUSD-L": 1279,                        # crypto
    "ACB": 1288,                             # stock
    "CGC": 1289,                             # stock
    "CRON": 1290,                            # stock
    "MJ": 1292,                              # etf
    "TLRY": 1293,                            # stock
    "BUD": 1294,                             # stock
    "LYFT": 1313,                            # stock
    "PINS": 1315,                            # stock
    "ZM": 1316,                              # stock
    "UBER": 1334,                            # stock
    "MELI": 1335,                            # stock
    "BYND": 1336,                            # stock
    "ATOMUSD-L": 1340,                       # crypto
    "EURUSD-AUDCAD-GBPCHF": 1341,            # public
    "EURUSD-OTC-AUDCAD-OTC-GBPJPY-OTC": 1342,# public
    "EURUSD-OTC-L": 1345,                    # opcode
    "EURJPY-OTC-L": 1346,                    # opcode
    "EURGBP-OTC-L": 1347,                    # opcode
    "AUDCAD-OTC-L": 1348,                    # opcode
    "SEDG": 1354,                            # stock
    "W": 1357,                               # stock
    "USDXOF": 1378,                          # forex
    "USDXOF-OTC": 1379,                      # forex
    "USDZAR-OTC": 1380,                      # forex
    "USDSGD-OTC": 1381,                      # forex
    "USDHKD-OTC": 1382,                      # forex
    "USDINR-OTC": 1383,                      # forex
    "AZN": 1386,                             # stock
    "BNTX": 1387,                            # stock
    "DOCU": 1388,                            # stock
    "SHOP": 1389,                            # stock
    "TTWO": 1390,                            # stock
    "JKS": 1391,                             # stock
    "ETSY": 1392,                            # stock
    "DPZ": 1393,                             # stock
    "GOLD": 1394,                            # stock
    "MGM": 1395,                             # stock
    "SPCE": 1396,                            # stock
    "PENN": 1397,                            # stock
    "AMC": 1400,                             # stock
    "GME": 1401,                             # stock
    "BB:US": 1402,                           # stock
    "NOK:US": 1403,                          # opcode
    "COIN": 1404,                            # stock
    "DOTUSD-L": 1405,                        # crypto
    "DOGEUSD-L": 1406,                       # crypto
    "UNIUSD-L": 1407,                        # crypto
    "LINKUSD-L": 1408,                       # crypto
    "VETUSD-L": 1409,                        # opcode
    "FILUSD-L": 1410,                        # crypto
    "ETCUSD-L": 1411,                        # opcode
    "MKRUSD-L": 1412,                        # opcode
    "HOOD": 1416,                            # stock
    "CLPUSD": 1419,                          # forex
    "BVN": 1435,                             # stock
    "KOF": 1437,                             # stock
    "YPF": 1439,                             # stock
    "TV": 1440,                              # stock
    "CIB": 1442,                             # stock
    "CX": 1443,                              # stock
    "BCH": 1444,                             # stock
    "FMX": 1445,                             # stock
    "EC": 1446,                              # stock
    "AMX": 1447,                             # stock
    "RELX": 1450,                            # stock
    "DECK": 1457,                            # stock
    "FIVE": 1460,                            # stock
    "COLM": 1464,                            # stock
    "DUOL": 1466,                            # stock
    "USSPX500:N": 1470,                      # index
    "USNDAQ100:N": 1471,                     # index
    "US30:N": 1472,                          # index
    "US2000:N": 1473,                        # index
    "SPAIN35:N": 1474,                       # index
    "UK100:N": 1475,                         # index
    "JAPAN225:N": 1476,                      # index
    "HONGKONG33:N": 1477,                    # index
    "GERMANY30:N": 1478,                     # index
    "FRANCE40:N": 1479,                      # index
    "EURO50:N": 1480,                        # index
    "AUS200:N": 1481,                        # index
    "S1:N": 1482,                            # commodity
    "W1:N": 1483,                            # commodity
    "C1:N": 1484,                            # commodity
    "XNGUSD:N": 1485,                        # commodity
    "HG1:N": 1486,                           # commodity
    "XAGUSD:N": 1487,                        # commodity
    "BTCUSD-OTC-L": 1520,                    # opcode
    "ETHUSD-OTC-L": 1521,                    # opcode
    "USDVND": 1522,                          # forex
    "USDARS": 1524,                          # forex
    "USDDOP": 1525,                          # forex
    "USDKRW": 1528,                          # forex
    "APTUSD": 1531,                          # crypto
    "ATOMUSD": 1532,                         # crypto
    "AVAXUSD": 1533,                         # crypto
    "AXSUSD": 1534,                          # crypto
    "BNBUSD": 1535,                          # crypto
    "DOGEUSD": 1536,                         # crypto
    "DOTUSD": 1537,                          # crypto
    "LINKUSD": 1538,                         # crypto
    "MANAUSD": 1539,                         # crypto
    "MATICUSD": 1540,                        # crypto
    "NEARUSD": 1541,                         # crypto
    "SANDUSD": 1542,                         # crypto
    "SOLUSD": 1543,                          # crypto
    "PENUSD-OTC-L": 1545,                    # opcode
    "USDBRL-OTC-L": 1546,                    # opcode
    "USDCOP-OTC-L": 1547,                    # opcode
    "USDMXN-OTC-L": 1548,                    # opcode
    "APTUSD-L": 1555,                        # crypto
    "AVAXUSD-L": 1556,                       # crypto
    "AXSUSD-L": 1557,                        # crypto
    "PEPEUSD-L": 1584,                       # crypto
    "PAH3d": 1585,                           # stock
    "PUMd": 1586,                            # stock
    "RNOp": 1587,                            # stock
    "AMGa": 1589,                            # stock
    "BOSSd": 1590,                           # stock
    "SRT3d": 1591,                           # stock
    "HEN3d": 1592,                           # stock
    "BASd": 1594,                            # stock
    "RWEd": 1595,                            # stock
    "HNR1d": 1597,                           # stock
    "VNAd": 1598,                            # stock
    "FMEd": 1599,                            # stock
    "TLXd": 1601,                            # stock
    "MTXd": 1602,                            # stock
    "RHMd": 1603,                            # stock
    "BNRd": 1604,                            # stock
    "DHERd": 1605,                           # stock
    "AFXd": 1607,                            # stock
    "EVKd": 1608,                            # stock
    "NEMd": 1609,                            # stock
    "ZALd": 1610,                            # stock
    "G1Ad": 1611,                            # stock
    "FRAd": 1612,                            # stock
    "SDFd": 1613,                            # stock
    "MCp": 1614,                             # stock
    "ASMLa": 1615,                           # stock
    "RMSp": 1616,                            # stock
    "PRXa": 1617,                            # stock
    "TTEp": 1618,                            # stock
    "SAPd": 1619,                            # stock
    "SANp": 1620,                            # stock
    "AP2d": 1622,                            # stock
    "ITXe": 1623,                            # stock
    "SUp": 1625,                             # stock
    "AIp": 1626,                             # stock
    "KERp": 1628,                            # stock
    "ELp": 1629,                             # stock
    "IBEe": 1630,                            # stock
    "BNPp": 1632,                            # stock
    "CSp": 1634,                             # stock
    "DGp": 1635,                             # stock
    "SHLd": 1636,                            # stock
    "RENa": 1638,                            # stock
    "RIp": 1639,                             # stock
    "DSYp": 1640,                            # stock
    "ISPm": 1641,                            # stock
    "MUV2d": 1642,                           # stock
    "STMPAp": 1643,                          # stock
    "UMGa": 1645,                            # stock
    "INGAa": 1646,                           # stock
    "BNp": 1647,                             # stock
    "ENGIp": 1648,                           # stock
    "DB1d": 1649,                            # stock
    "ACAp": 1650,                            # stock
    "ADa": 1651,                             # stock
    "WKLa": 1653,                            # stock
    "CAPp": 1654,                            # stock
    "ORAp": 1655,                            # stock
    "Gm": 1656,                              # stock
    "HOp": 1657,                             # stock
    "AMSe": 1659,                            # stock
    "CABKe": 1660,                           # stock
    "DTGd": 1661,                            # stock
    "VIEp": 1662,                            # stock
    "ARRDd": 1663,                           # stock
    "LRp": 1664,                             # stock
    "REPe": 1665,                            # stock
    "MONCm": 1666,                           # stock
    "GLEp": 1668,                            # stock
    "SGOp": 1669,                            # stock
    "NTGYe": 1670,                           # stock
    "CLNXe": 1671,                           # stock
    "AENAe": 1672,                           # stock
    "ELEe": 1673,                            # stock
    "MLp": 1674,                             # stock
    "FERe": 1675,                            # stock
    "PUBp": 1677,                            # stock
    "ASMa": 1678,                            # stock
    "EXOa": 1679,                            # stock
    "ENRd": 1680,                            # stock
    "BOLp": 1681,                            # stock
    "SRGm": 1682,                            # stock
    "TENm": 1683,                            # stock
    "OCIa": 1684,                            # stock
    "TRNm": 1685,                            # stock
    "AMp": 1686,                             # stock
    "PHIAa": 1687,                           # stock
    "FREd": 1688,                            # stock
    "EDENp": 1689,                           # stock
    "SWp": 1691,                             # stock
    "KPNa": 1692,                            # stock
    "ABNa": 1693,                            # stock
    "CPRm": 1694,                            # stock
    "TEPp": 1695,                            # stock
    "ADPp": 1696,                            # stock
    "AKZAa": 1697,                           # stock
    "BVIp": 1698,                            # stock
    "ERFp": 1699,                            # stock
    "ENp": 1700,                             # stock
    "ANEe": 1701,                            # stock
    "BIMp": 1753,                            # stock
    "WLNp": 1755,                            # stock
    "PRYm": 1756,                            # stock
    "ANAe": 1757,                            # stock
    "NNa": 1758,                             # stock
    "RANDa": 1759,                           # stock
    "FGRp": 1760,                            # stock
    "NEXIm": 1761,                           # stock
    "ALOp": 1762,                            # stock
    "FBKm": 1764,                            # stock
    "AGNa": 1765,                            # stock
    "RCOp": 1766,                            # stock
    "IMCDa": 1767,                           # stock
    "GETp": 1768,                            # stock
    "ACSe": 1770,                            # stock
    "RECm": 1771,                            # stock
    "MBm": 1772,                             # stock
    "WCHd": 1773,                            # stock
    "AMPm": 1776,                            # stock
    "URWp": 1777,                            # stock
    "AKEp": 1778,                            # stock
    "RXLp": 1780,                            # stock
    "RRTLd": 1782,                           # stock
    "BESIa": 1783,                           # stock
    "LDOm": 1784,                            # stock
    "BMEDm": 1785,                           # stock
    "SABe": 1791,                            # stock
    "ASRNLa": 1792,                          # stock
    "IPm": 1793,                             # stock
    "BAMIm": 1794,                           # stock
    "EVDd": 1795,                            # stock
    "BC8d": 1796,                            # stock
    "CTPNVa": 1798,                          # stock
    "COVp": 1799,                            # stock
    "INWm": 1800,                            # stock
    "3988.xhkg": 1801,                       # stock
    "857.xhkg": 1802,                        # stock
    "2318.xhkg": 1803,                       # stock
    "700.xhkg": 1804,                        # stock
    "1299.xhkg": 1805,                       # stock
    "1211.xhkg": 1806,                       # stock
    "939.xhkg": 1807,                        # stock
    "2628.xhkg": 1808,                       # stock
    "386.xhkg": 1810,                        # stock
    "1088.xhkg": 1811,                       # stock
    "175.xhkg": 1813,                        # stock
    "5.xhkg": 1814,                          # stock
    "1398.xhkg": 1815,                       # stock
    "3690.xhkg": 1816,                       # stock
    "1810.xhkg": 1817,                       # stock
    "9988.xhkg": 1818,                       # stock
    "23.xhkg": 1819,                         # stock
    "2388.xhkg": 1820,                       # stock
    "688.xhkg": 1821,                        # stock
    "390.xhkg": 1822,                        # stock
    "1109.xhkg": 1823,                       # stock
    "267.xhkg": 1826,                        # stock
    "1.xhkg": 1827,                          # stock
    "2.xhkg": 1828,                          # stock
    "27.xhkg": 1830,                         # stock
    "1044.xhkg": 1832,                       # stock
    "9618.xhkg": 1833,                       # stock
    "1024.xhkg": 1834,                       # stock
    "66.xhkg": 1835,                         # stock
    "1928.xhkg": 1836,                       # stock
    "992.xhkg": 1837,                        # stock
    "1288.xhkg": 1838,                       # stock
    "241.xhkg": 1839,                        # stock
    "9888.xhkg": 1840,                       # stock
    "3328.xhkg": 1841,                       # stock
    "293.xhkg": 1842,                        # stock
    "1816.xhkg": 1843,                       # stock
    "1113.xhkg": 1845,                       # stock
    "1093.xhkg": 1846,                       # stock
    "388.xhkg": 1847,                        # stock
    "2328.xhkg": 1848,                       # stock
    "2338.xhkg": 1849,                       # stock
    "288.xhkg": 1850,                        # stock
    "2015.xhkg": 1851,                       # stock
    "9866.xhkg": 1852,                       # stock
    "9868.xhkg": 1853,                       # stock
    "763.xhkg": 1854,                        # stock
    "2018.xhkg": 1855,                       # stock
    "XAUUSD-OTC": 1857,                      # commodity
    "XAGUSD-OTC": 1858,                      # commodity
    "USOUSD-OTC": 1859,                      # commodity
    "EURUSD-op": 1861,                       # forex
    "EURGBP-op": 1862,                       # forex
    "XNGUSD-OTC": 1863,                      # commodity
    "EURJPY-op": 1864,                       # forex
    "USDJPY-op": 1865,                       # forex
    "GBPJPY-op": 1866,                       # forex
    "GBPUSD-op": 1867,                       # forex
    "AUDCAD-op": 1868,                       # forex
    "AUDJPY-op": 1869,                       # forex
    "AUDUSD-op": 1870,                       # forex
    "CADCHF-op": 1871,                       # forex
    "CHFJPY-op": 1873,                       # forex
    "EURAUD-op": 1874,                       # forex
    "EURCAD-op": 1875,                       # forex
    "EURCHF-op": 1876,                       # forex
    "GBPAUD-op": 1877,                       # forex
    "USDCAD-op": 1878,                       # forex
    "USDCHF-op": 1879,                       # forex
    "GBPNZD-op": 1880,                       # forex
    "NZDCAD-op": 1881,                       # forex
    "NZDJPY-op": 1882,                       # forex
    "USDBRL-OP": 1883,                       # opcode
    "AUDCHF-op": 1884,                       # forex
    "USDSEK-op": 1889,                       # forex
    "NZDUSD-op": 1896,                       # forex
    "GBPCAD-op": 1897,                       # forex
    "GBPCHF-op": 1898,                       # forex
    "AUDNZD-op": 1900,                       # forex
    "EURNZD-op": 1901,                       # forex
    "CISCO-OP": 1902,                        # opcode
    "CITI-op": 1903,                         # stock
    "SNAP-OP": 1904,                         # opcode
    "TESLA-op": 1905,                        # stock
    "MCDON-op": 1906,                        # stock
    "MORSTAN-op": 1907,                      # stock
    "ALIBABA-op": 1908,                      # stock
    "AMAZON-op": 1909,                       # stock
    "APPLE-op": 1910,                        # stock
    "BAIDU-op": 1911,                        # stock
    "XAUUSD-op": 1912,                       # commodity
    "USOUSD-op": 1914,                       # commodity
    "BTCUSD-op": 1916,                       # crypto
    "ETHUSD-op": 1918,                       # crypto
    "XRPUSD-op": 1921,                       # crypto
    "COKE-op": 1922,                         # stock
    "MSFT-op": 1923,                         # stock
    "NIKE-op": 1924,                         # stock
    "FACEBOOK-op": 1925,                     # stock
    "GOOGLE-op": 1926,                       # stock
    "GS-op": 1927,                           # stock
    "INTEL-op": 1928,                        # stock
    "JPM-op": 1929,                          # stock
    "AIG-OP": 1930,                          # opcode
    "UKOUSD-OTC": 1931,                      # commodity
    "GOOGLE-OTC": 1933,                      # stock
    "AMAZON-OTC": 1935,                      # stock
    "TESLA-OTC": 1936,                       # stock
    "FB-OTC": 1937,                          # stock
    "APPLE-OTC": 1938,                       # stock
    "SHIB/USD-L": 1939,                      # crypto
    "ETHUSD-OTC": 1941,                      # crypto
    "GBTC": 1942,                            # etf
    "IBIT": 1946,                            # etf
    "SP500-OTC": 1971,                       # index
    "USNDAQ100-OTC": 1972,                   # index
    "US30-OTC": 1973,                        # index
    "CARDANO-OTC": 1974,                     # crypto
    "SHIBUSD-OTC": 1975,                     # crypto
    "TRON-OTC": 1976,                        # crypto
    "DOGECOIN-OTC": 1977,                    # crypto
    "SOLUSD-OTC": 1978,                      # crypto
    "BTCUSD-XL": 1979,                       # crypto
    "SHIBUSD": 1997,                         # crypto
    "WIFUSD-L": 2017,                        # crypto
    "JUPUSD-L": 2019,                        # crypto
    "ICPUSD-L": 2020,                        # crypto
    "IMXUSD-L": 2021,                        # crypto
    "INJUSD-L": 2022,                        # crypto
    "ARBUSD-L": 2023,                        # crypto
    "OPUSD-L": 2024,                         # crypto
    "SEIUSD-L": 2025,                        # crypto
    "BEAMUSD-L": 2026,                       # crypto
    "GALAUSD-L": 2027,                       # crypto
    "WLDUSD-L": 2028,                        # crypto
    "ORDIUSD-L": 2029,                       # crypto
    "PYTHUSD-L": 2031,                       # crypto
    "RONINUSD-L": 2032,                      # crypto
    "TIAUSD-L": 2033,                        # crypto
    "GRTUSD-L": 2034,                        # crypto
    "STXUSD-L": 2035,                        # crypto
    "MANAUSD-L": 2036,                       # crypto
    "MATICUSD-L": 2037,                      # crypto
    "NEARUSD-L": 2038,                       # crypto
    "SANDUSD-L": 2039,                       # crypto
    "SOLUSD-L": 2040,                        # crypto
    "Reddit": 2041,                          # stock
    "SP35-OTC": 2044,                        # index
    "FR40-OTC": 2045,                        # index
    "GER30-OTC": 2046,                       # index
    "UK100-OTC": 2047,                       # index
    "AUS200-OTC": 2048,                      # index
    "HK33-OTC": 2049,                        # index
    "EU50-OTC": 2050,                        # index
    "JP225-OTC": 2051,                       # index
    "AXBl": 2052,                            # stock
    "LTODl": 2054,                           # stock
    "WIT": 2058,                             # stock
    "HDB": 2059,                             # stock
    "IBN": 2060,                             # stock
    "INFY": 2061,                            # stock
    "Dollar_Index": 2062,                    # index
    "Yen_Index": 2063,                       # index
    "US30/JP225": 2064,                      # index
    "US100/JP225": 2065,                     # index
    "US500/JP225": 2066,                     # index
    "AMZN/ALIBABA": 2067,                    # stock
    "AMZN/EBAY": 2068,                       # stock
    "NVDA/AMD": 2069,                        # stock
    "GOOGLE/MSFT": 2070,                     # stock
    "XAU/XAG": 2071,                         # commodity
    "TESLA/FORD": 2072,                      # stock
    "MSFT/AAPL": 2073,                       # stock
    "INTEL/IBM": 2074,                       # stock
    "NFLX/AMZN": 2075,                       # stock
    "META/GOOGLE": 2076,                     # stock
    "TONUSD": 2077,                          # crypto
    "GER30/UK100": 2078,                     # index
    "US30/JP225-OTC": 2079,                  # index
    "US100/JP225-OTC": 2080,                 # index
    "US500/JP225-OTC": 2081,                 # index
    "AMZN/ALIBABA-OTC": 2082,                # stock
    "AMZN/EBAY-OTC": 2083,                   # stock
    "NVDA/AMD-OTC": 2084,                    # stock
    "GOOGLE/MSFT-OTC": 2085,                 # stock
    "XAU/XAG-OTC": 2086,                     # commodity
    "TESLA/FORD-OTC": 2087,                  # stock
    "MSFT/AAPL-OTC": 2088,                   # stock
    "INTEL/IBM-OTC": 2089,                   # stock
    "NFLX/AMZN-OTC": 2090,                   # stock
    "TONUSD-OTC": 2091,                      # crypto
    "GER30/UK100-OTC": 2093,                 # index
    "META/GOOGLE-OTC": 2094,                 # stock
    "NOTCOIN": 2095,                         # crypto
    "NOTCOIN-OTC": 2096,                     # crypto
    "BIDU-OTC": 2097,                        # stock
    "INTEL-OTC": 2098,                       # stock
    "MSFT-OTC": 2099,                        # stock
    "CITI-OTC": 2100,                        # stock
    "COKE-OTC": 2101,                        # stock
    "JPM-OTC": 2102,                         # stock
    "MCDON-OTC": 2103,                       # stock
    "MORSTAN-OTC": 2104,                     # stock
    "NIKE-OTC": 2105,                        # stock
    "ALIBABA-OTC": 2106,                     # stock
    "XRPUSD-OTC": 2107,                      # crypto
    "US2000-OTC": 2108,                      # index
    "AIG-OTC": 2109,                         # stock
    "GS-OTC": 2110,                          # stock
    "AUDUSD-OTC": 2111,                      # forex
    "USDCAD-OTC": 2112,                      # forex
    "AUDJPY-OTC": 2113,                      # forex
    "GBPCAD-OTC": 2114,                      # forex
    "GBPCHF-OTC": 2115,                      # forex
    "GBPAUD-OTC": 2116,                      # forex
    "EURCAD-OTC": 2117,                      # forex
    "CHFJPY-OTC": 2118,                      # forex
    "CADCHF-OTC": 2119,                      # forex
    "EURAUD-OTC": 2120,                      # forex
    "USDNOK-OTC": 2121,                      # forex
    "EURNZD-OTC": 2122,                      # forex
    "USDSEK-OTC": 2123,                      # forex
    "USDTRY-OTC": 2124,                      # forex
    "SNAP-OTC": 2125,                        # stock
    "LTCUSD-OTC": 2126,                      # crypto
    "EOSUSD-OTC": 2127,                      # crypto
    "USDPLN-OTC": 2128,                      # forex
    "AUDCHF-OTC": 2129,                      # forex
    "AUDNZD-OTC": 2130,                      # forex
    "EURCHF-OTC": 2131,                      # forex
    "GBPNZD-OTC": 2132,                      # forex
    "EURGBP_GS": 2133,                       # opcode
    "CADJPY-OTC": 2136,                      # forex
    "NZDCAD-OTC": 2137,                      # forex
    "NZDJPY-OTC": 2138,                      # forex
    "ICPUSD-OTC": 2139,                      # crypto
    "IMXUSD-OTC": 2140,                      # crypto
    "JUPUSD-OTC": 2141,                      # crypto
    "BONKUSD-OTC": 2142,                     # crypto
    "LINKUSD-OTC": 2143,                     # crypto
    "WIFUSD-OTC": 2144,                      # crypto
    "PEPEUSD-OTC": 2145,                     # crypto
    "FLOKIUSD-OTC": 2146,                    # crypto
    "GALAUSD-OTC": 2147,                     # opcode
    "BCHUSD-OTC": 2148,                      # crypto
    "DOTUSD-OTC": 2149,                      # crypto
    "ATOMUSD-OTC": 2150,                     # crypto
    "INJUSD-OTC": 2151,                      # crypto
    "SEIUSD-OTC": 2152,                      # crypto
    "IOTAUSD-OTC": 2153,                     # crypto
    "BEAMUSD-OTC": 2154,                     # opcode
    "DASHUSD-OTC": 2155,                     # crypto
    "ARBUSD-OTC": 2156,                      # crypto
    "WLDUSD-OTC": 2157,                      # crypto
    "ORDIUSD-OTC": 2158,                     # crypto
    "SATSUSD-OTC": 2159,                     # crypto
    "PYTHUSD-OTC": 2160,                     # crypto
    "RONINUSD-OTC": 2161,                    # crypto
    "TIAUSD-OTC": 2162,                      # crypto
    "MANAUSD-OTC": 2163,                     # crypto
    "SANDUSD-OTC": 2164,                     # crypto
    "GRTUSD-OTC": 2165,                      # crypto
    "STXUSD-OTC": 2166,                      # crypto
    "MATICUSD-OTC": 2167,                    # crypto
    "NEARUSD-OTC": 2168,                     # crypto
    "GGAL": 2169,                            # stock
    "BMA": 2170,                             # stock
    "PAM": 2171,                             # stock
    "TEO": 2172,                             # stock
    "TGS": 2173,                             # stock
    "PBR": 2174,                             # stock
    "BBD": 2175,                             # stock
    "ABEV": 2176,                            # stock
    "VALE": 2177,                            # stock
    "NU": 2178,                              # stock
    "GPRK": 2179,                            # stock
    "VIST": 2180,                            # stock
    "EURTHB-OTC": 2181,                      # forex
    "USDTHB-OTC": 2182,                      # forex
    "JPYTHB-OTC": 2183,                      # forex
    "TRUMPVSHARRIS-OTC": 2185,               # opcode
    "USDARS-OTC": 2186,                      # forex
    "CLPUSD-OTC": 2187,                      # forex
    "USDDOP-OTC": 2188,                      # forex
    "HMSTR-OTC": 2192,                       # opcode
    "CHFNOK-OTC": 2200,                      # forex
    "NOKJPY-OTC": 2201,                      # forex
    "NZDCHF-OTC": 2202,                      # forex
    "GAUUSD": 2230,                          # commodity
    "GAGUSD": 2231,                          # commodity
    "TRUMPUSD-L": 2264,                      # crypto
    "TRUMPUSD-OTC": 2265,                    # crypto
    "MELANIAUSD-L": 2266,                    # crypto
    "MELANIAUSD-OTC": 2267,                  # crypto
    "RAYDIUMUSD-L": 2268,                    # crypto
    "ONDOUSD-L": 2269,                       # crypto
    "BTCUSD-OTC-op": 2270,                   # crypto
    "DYDXUSD-L": 2271,                       # crypto
    "FARTCOINUSD-L": 2273,                   # crypto
    "PENGUUSD-L": 2274,                      # crypto
    "XMRUSD-L": 2275,                        # crypto
    "ONDOUSD-OTC": 2276,                     # crypto
    "DYDXUSD-OTC": 2277,                     # crypto
    "ONYXCOINUSD-OTC": 2278,                 # crypto
    "FARTCOINUSD-OTC": 2279,                 # crypto
    "PENGUUSD-OTC": 2280,                    # crypto
    "SUIUSD-L": 2281,                        # crypto
    "HBARUSD-L": 2282,                       # crypto
    "RENDERUSD-L": 2284,                     # crypto
    "TAOUSD-L": 2285,                        # crypto
    "RAYDIUMUSD-OTC": 2286,                  # crypto
    "SUIUSD-OTC": 2287,                      # crypto
    "HBARUSD-OTC": 2288,                     # crypto
    "FETUSD-OTC": 2289,                      # crypto
    "RENDERUSD-OTC": 2290,                   # crypto
    "TAOUSD-OTC": 2291,                      # crypto
    "Spark_Coin": 2293,                      # crypto
    "Hyper_Coin": 2294,                      # crypto
    "USDBRL-OTC": 2298,                      # forex
    "USDCOP-OTC": 2299,                      # forex
    "USDMXN-OTC": 2300,                      # forex
    "PENUSD-OTC": 2301,                      # forex
    "BTCUSD-op_2": 2302,                     # crypto
    "LABUBUUSD-OTC": 2304,                   # crypto
    "SOLUSD-Bitfinex": 2305,                 # crypto
    "DOGEUSD-bitfinex": 2306,                # crypto
    "LINKUSD-bitfinex": 2307,                # crypto
    "Klarna": 2308,                          # stock
    "Formula_One_Group": 2309,               # stock
    "Palantir": 2310,                        # stock
    "KLARNA-OTC": 2311,                      # stock
    "FWONA-OTC": 2312,                       # stock
    "PLTR-OTC": 2313,                        # stock
    "Magnificent_7": 2314,                   # stock
    "Airlines": 2315,                        # stock
    "Casinos": 2316,                         # stock
    "Cannabis": 2317,                        # stock
    "Uranium": 2318,                         # stock
    "MAGNIFICENT7-OTC": 2319,                # stock
    "AIRLINES-OTC": 2320,                    # stock
    "CASINOS-OTC": 2321,                     # stock
    "CANNABIS-OTC": 2322,                    # stock
    "URANIUM-OTC": 2323,                     # stock
    "XXI": 2324,                             # stock
    "DXY": 2325,                             # index
    "XPDUSD": 2326,                          # commodity
    "XPTUSD-OTC": 2327,                      # commodity
    "XPDUSD-OTC": 2328,                      # commodity
    "JXY": 2331,                             # index
    "EXY": 2332,                             # index
    "BXY": 2333,                             # index
    "CXY": 2334,                             # index
    "AXY": 2335,                             # index
    "SMCI": 2336,                            # stock
    "SOFI": 2337,                            # stock
    "DJT": 2338,                             # stock
    "SOUN": 2339,                            # stock
    "BBAI": 2340,                            # stock
    "HIMS": 2341,                            # stock
    "IONQ": 2342,                            # stock
    "OPEN": 2343,                            # stock
    "RGTI": 2344,                            # stock
    "RIVN": 2345,                            # stock
    "OKLO": 2346,                            # stock
    "TSM": 2347,                             # stock
    "ASTS": 2348,                            # stock
    "QBTS": 2349,                            # stock
    "RKLB": 2350,                            # stock
    "ACHR": 2351,                            # stock
    "APLD": 2352,                            # stock
    "CRWV": 2353,                            # stock
    "JOBY": 2354,                            # stock
    "LCID": 2355,                            # stock
    "MSTR": 2356,                            # stock
    "NBIS": 2357,                            # stock
    "CAVA": 2358,                            # stock
    "ET": 2359,                              # stock
    "OXY": 2360,                             # stock
    "PLUG": 2361,                            # stock
    "RIOT": 2362,                            # stock
    "CRCL": 2363,                            # stock
    "FIG": 2364,                             # stock
    "LUNR": 2365,                            # stock
    "MRVL": 2366,                            # stock
    "QS": 2367,                              # stock
    "SNOW": 2368,                            # stock
    "TEM": 2369,                             # stock
    "TTD": 2370,                             # stock
    "VST": 2371,                             # stock
    "FUBO": 2372,                            # stock
    "GEV": 2373,                             # stock
    "ARM": 2374,                             # stock
    "LULU": 2375,                            # stock
    "CVNA": 2376,                            # stock
    "WOLF": 2377,                            # stock
    "HOLO": 2378,                            # stock
    "Binance_Coin": 2381,                    # crypto
    "Uniswap": 2386,                         # crypto
    "Stellar": 2387,                         # crypto
    "Toncoin": 2391,                         # crypto
    "AAVE-L": 2392,                          # crypto
    "Sui": 2395,                             # crypto
    "PEPE": 2397,                            # crypto
    "IEF": 2398,                             # etf
    "SHY": 2399,                             # etf
    "ARKK": 2400,                            # etf
    "MU-OTC": 2402,                          # stock
    "NVDA-OTC": 2403,                        # stock
    "GEV-OTC": 2404,                         # stock
    "Western_Digital_Corporation": 2405,     # stock
    "Sandisk_Corporation": 2406,             # stock
    "SNDK-OTC": 2407,                        # stock
    "WDC-OTC": 2408,                         # stock
    "USDIDR-OTC": 2409,                      # forex
    "COCOA": 2410,                           # commodity
    "COFFEE": 2411,                          # commodity
    "COTTON": 2412,                          # commodity
    "SUGAR": 2413,                           # commodity
    "COCOA-OTC": 2414,                       # commodity
    "COFFEE-OTC": 2415,                      # commodity
    "COTTON-OTC": 2416,                      # commodity
    "SUGAR-OTC": 2417,                       # commodity
    "Kaspa-L": 2423,                         # crypto
    "MS_Bitcoin_ETF": 2424,                  # etf
    "iShares_Ethereum_Trust_ETF": 2425,      # etf
    "AAVEUSD": 2426,                         # crypto
    "HBARUSD": 2427,                         # crypto
    "ETHBTC-OTC": 2428,                      # opcode
}
